events = [
    # --- 20 Marriage Events ---
    {"title": "Marriage", "location": "Lotus Banquet Hall, Delhi", "description": "Traditional Indian wedding with cultural festivities.", "capacity": 300, "image": "marriage/couple_1.jpg"},
    {"title": "Marriage", "location": "Royal Garden, Mumbai", "description": "Lavish destination wedding celebration.", "capacity": 500, "image": "marriage/couple_2.jpg"},
    {"title": "Marriage", "location": "Golden Orchid, Jaipur", "description": "Rajasthani-themed wedding event.", "capacity": 350, "image": "marriage/couple_3.jpg"},
    {"title": "Marriage", "location": "Pearl Hall, Kolkata", "description": "Family gathering with sangeet and mehendi.", "capacity": 250, "image": "marriage/couple_4.jpg"},
    {"title": "Marriage", "location": "Vivanta Resort, Goa", "description": "Beach wedding with live music.", "capacity": 200, "image": "marriage/couple_5.jpg"},
    {"title": "Marriage", "location": "Grand Ballroom, Chennai", "description": "South Indian wedding with classical performance.", "capacity": 400, "image": "marriage/couple_1.jpg"},
    {"title": "Marriage", "location": "Rose Valley, Lucknow", "description": "Elegant decor and large guest list.", "capacity": 320, "image": "marriage/couple_2.jpg"},
    {"title": "Marriage", "location": "Ocean View, Kochi", "description": "Christian wedding with a serene backdrop.", "capacity": 220, "image": "marriage/couple_3.jpg"},
    {"title": "Marriage", "location": "Hilltop Resort, Shimla", "description": "Mountain destination wedding.", "capacity": 180, "image": "marriage/couple_4.jpg"},
    {"title": "Marriage", "location": "Amber Palace, Jaipur", "description": "Royal-themed traditional wedding.", "capacity": 450, "image": "marriage/couple_5.jpg"},
    {"title": "Marriage", "location": "Palm Greens, Ahmedabad", "description": "Eco-friendly green wedding.", "capacity": 280, "image": "marriage/couple_1.jpg"},
    {"title": "Marriage", "location": "Sky Lounge, Pune", "description": "Modern rooftop wedding ceremony.", "capacity": 260, "image": "marriage/couple_2.jpg"},
    {"title": "Marriage", "location": "Silver Bells, Bhopal", "description": "Musical wedding night with live bands.", "capacity": 310, "image": "marriage/couple_3.jpg"},
    {"title": "Marriage", "location": "White Lotus, Hyderabad", "description": "Hyderabadi cuisine wedding special.", "capacity": 330, "image": "marriage/couple_4.jpg"},
    {"title": "Marriage", "location": "Gardenia Park, Raipur", "description": "Simple and elegant event with close relatives.", "capacity": 150, "image": "marriage/couple_5.jpg"},
    {"title": "Marriage", "location": "Sapphire Retreat, Mysuru", "description": "Traditional Kannada wedding experience.", "capacity": 190, "image": "marriage/couple_1.jpg"},
    {"title": "Marriage", "location": "Zenith Palace, Nagpur", "description": "Marathi traditions with modern twists.", "capacity": 275, "image": "marriage/couple_2.jpg"},
    {"title": "Marriage", "location": "Sunset Lawns, Vizag", "description": "Evening wedding with beachside vows.", "capacity": 300, "image": "marriage/couple_3.jpg"},
    {"title": "Marriage", "location": "Orchid Valley, Indore", "description": "Flower-themed wedding celebration.", "capacity": 350, "image": "marriage/couple_4.jpg"},
    {"title": "Marriage", "location": "Blue Lagoon, Surat", "description": "A blend of culture and modern charm.", "capacity": 230, "image": "marriage/couple_5.jpg"},

    # --- 20 Birthday Events ---
    {"title": "Birthday", "location": "Fun Fiesta, Mumbai", "description": "Kids' birthday with games and magic show.", "capacity": 40, "image": "birthday/birthday_6.jpg"},
    {"title": "Birthday", "location": "Jungle Zone, Delhi", "description": "Animal-themed celebration with mascots.", "capacity": 35, "image": "birthday/birthday_7.jpg"},
    {"title": "Birthday", "location": "Sky High Lounge, Bangalore", "description": "Adults-only rooftop birthday bash.", "capacity": 60, "image": "birthday/birthday_8.jpg"},
    {"title": "Birthday", "location": "Balloon Party Hall, Chennai", "description": "Colorful birthday event with clowns.", "capacity": 45, "image": "birthday/birthday_9.jpg"},
    {"title": "Birthday", "location": "Water Kingdom, Pune", "description": "Pool party with water rides.", "capacity": 55, "image": "birthday/birthday_10.jpg"},
    {"title": "Birthday", "location": "Urban Café, Hyderabad", "description": "Classy birthday dinner with live music.", "capacity": 50, "image": "birthday/birthday_6.jpg"},
    {"title": "Birthday", "location": "WonderLand Park, Noida", "description": "Adventure-themed celebration for teens.", "capacity": 70, "image": "birthday/birthday_7.jpg"},
    {"title": "Birthday", "location": "Magic World, Jaipur", "description": "Entertainer-filled fun party for kids.", "capacity": 30, "image": "birthday/birthday_8.jpg"},
    {"title": "Birthday", "location": "Café Neon, Kolkata", "description": "Neon-themed 21st birthday party.", "capacity": 65, "image": "birthday/birthday_9.jpg"},
    {"title": "Birthday", "location": "Retro Bar, Ahmedabad", "description": "Retro music and dance-themed celebration.", "capacity": 55, "image": "birthday/birthday_10.jpg"},
    {"title": "Birthday", "location": "VR Zone, Kochi", "description": "Virtual reality gaming party.", "capacity": 20, "image": "birthday/birthday_6.jpg"},
    {"title": "Birthday", "location": "Fantasy Dome, Indore", "description": "Fantasy cosplay birthday event.", "capacity": 40, "image": "birthday/birthday_7.jpg"},
    {"title": "Birthday", "location": "Sky Deck, Vizag", "description": "High-rise view birthday dinner.", "capacity": 35, "image": "birthday/birthday_8.jpg"},
    {"title": "Birthday", "location": "Glow Arena, Surat", "description": "Glow-in-the-dark birthday night.", "capacity": 25, "image": "birthday/birthday_9.jpg"},
    {"title": "Birthday", "location": "Open Grounds, Bhopal", "description": "Outdoor celebration with bonfire.", "capacity": 50, "image": "birthday/birthday_10.jpg"},
    {"title": "Birthday", "location": "Pizza Planet, Lucknow", "description": "Food-themed party for all ages.", "capacity": 45, "image": "birthday/birthday_6.jpg"},
    {"title": "Birthday", "location": "City Club, Mysuru", "description": "Elegant club celebration for adults.", "capacity": 40, "image": "birthday/birthday_7.jpg"},
    {"title": "Birthday", "location": "Lakeview Hall, Raipur", "description": "Quiet lakeside party.", "capacity": 30, "image": "birthday/birthday_8.jpg"},
    {"title": "Birthday", "location": "Gamer’s Den, Nagpur", "description": "Gaming party with PS5/Xbox.", "capacity": 20, "image": "birthday/birthday_9.jpg"},
    {"title": "Birthday", "location": "Skate Arena, Trivandrum", "description": "Skate-themed fun party.", "capacity": 25, "image": "birthday/birthday_10.jpg"},

    # --- 10 Meetup Events ---
    {"title": "Meetup", "location": "Tech Hub, Bangalore", "description": "AI & ML community gathering.", "capacity": 80, "image": "meetup/meetup_1.jpg"},
    {"title": "Meetup", "location": "Innovation Café, Hyderabad", "description": "Startup founders and investors meetup.", "capacity": 100, "image": "meetup/meetup_3.jpg"},
    {"title": "Meetup", "location": "Writers’ Circle, Delhi", "description": "Poetry and fiction enthusiasts meet.", "capacity": 40, "image": "meetup/meetup_4.jpg"},
    {"title": "Meetup", "location": "Art Basement, Mumbai", "description": "Artists showcase and collaborate.", "capacity": 60, "image": "meetup/meetup_5.jpg"},
    {"title": "Meetup", "location": "Green Talk Café, Pune", "description": "Sustainability and green living meet.", "capacity": 70, "image": "meetup/meetup_1.jpg"},
    {"title": "Meetup", "location": "Book Lounge, Chennai", "description": "Book lovers and critics circle.", "capacity": 30, "image": "meetup/meetup_3.jpg"},
    {"title": "Meetup", "location": "FilmNest, Kolkata", "description": "Indie filmmakers discussion.", "capacity": 50, "image": "meetup/meetup_4.jpg"},
    {"title": "Meetup", "location": "Dev Space, Jaipur", "description": "Open source dev hangout.", "capacity": 90, "image": "meetup/meetup_5.jpg"},
    {"title": "Meetup", "location": "Cloud Café, Noida", "description": "Cloud computing and DevOps meetup.", "capacity": 85, "image": "meetup/meetup_1.jpg"},
    {"title": "Meetup", "location": "UX Studio, Ahmedabad", "description": "Designers and UI/UX meet.", "capacity": 55, "image": "meetup/meetup_3.jpg"},

    # --- 10 Corporate Events ---
    {"type":"corporate","title": "Infosys", "location": "Convention Center, Bangalore", "description": "Annual general meeting and roadmap discussion.", "capacity": 500, "image": "corporate/corporate_1.jpg"},
    {"type":"corporate","title": "TCS", "location": "TCS Towers, Mumbai", "description": "Team building and client meet-up.", "capacity": 200, "image": "corporate/corporate_2.jpg"},
    {"type":"corporate","title": "Wipro", "location": "Wipro Campus, Hyderabad", "description": "Leadership summit and awards.", "capacity": 300, "image": "corporate/corporate_4.jpg"},
    {"type":"corporate","title": "HCL", "location": "HCL Auditorium, Noida", "description": "Quarterly performance review.", "capacity": 150, "image": "corporate/corporate_5.jpg"},
    {"type":"corporate","title": "Tech Mahindra", "location": "Tech Hub, Pune", "description": "Tech expo and innovation showcase.", "capacity": 400, "image": "corporate/corporate_1.jpg"},
    {"type":"corporate","title": "Zoho", "location": "Zoho Convention, Chennai", "description": "Product launch event.", "capacity": 250, "image": "corporate/corporate_2.jpg"},
    {"type":"corporate","title": "Paytm", "location": "Paytm Park, Delhi", "description": "Finance and fintech panel.", "capacity": 300, "image": "corporate/corporate_4.jpg"},
    {"type":"corporate","title": "Amazon India", "location": "Amazon HQ, Hyderabad", "description": "Hiring drive and business pitch.", "capacity": 350, "image": "corporate/corporate_5.jpg"},
    {"type":"corporate","title": "Google India", "location": "Google Campus, Bangalore", "description": "Developer conference.", "capacity": 600, "image": "corporate/corporate_1.jpg"},
    {"type":"corporate","title": "Microsoft India", "location": "Microsoft Tech Center, Mumbai", "description": "Tech showcase and AI bootcamp.", "capacity": 450, "image": "corporate/corporate_2.jpg"},

    # --- 10 Fashion Show Events ---
    {"title": "Fashion Show", "location": "Grand Plaza, Mumbai", "description": "Milan-inspired haute couture runway gala.", "capacity": 500, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "Taj Palace, Delhi", "description": "Bridal couture showcase with top designers.", "capacity": 400, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "ITC Gardenia, Bangalore", "description": "Vogue-style trend preview for spring/summer.", "capacity": 350, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "JW Marriott, Hyderabad", "description": "Luxury menswear collection launch.", "capacity": 300, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "Leela Palace, Chennai", "description": "Sustainable fashion runway event.", "capacity": 250, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "Oberoi, Kolkata", "description": "Ethnic wear fusion design showcase.", "capacity": 280, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "Westin, Pune", "description": "Streetwear meets high-fashion pop-up.", "capacity": 320, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "Park Hyatt, Goa", "description": "Resort & beachwear collection show.", "capacity": 200, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "Rambagh Palace, Jaipur", "description": "Royal Rajasthani designer label launch.", "capacity": 450, "image": "fashion_show.jpg"},
    {"title": "Fashion Show", "location": "ITC Grand, Ahmedabad", "description": "Textile heritage meets modern runway.", "capacity": 350, "image": "fashion_show.jpg"},

    # --- 10 Sports Events ---
    {"title": "Sports", "location": "DY Patil Stadium, Mumbai", "description": "Pro tennis championship final viewing.", "capacity": 5000, "image": "sports.jpg"},
    {"title": "Sports", "location": "Chinnaswamy Stadium, Bangalore", "description": "Corporate cricket league tournament.", "capacity": 3000, "image": "sports.jpg"},
    {"title": "Sports", "location": "Jawaharlal Nehru Stadium, Delhi", "description": "Inter-college athletics championship.", "capacity": 8000, "image": "sports.jpg"},
    {"title": "Sports", "location": "Rajiv Gandhi Stadium, Hyderabad", "description": "Football league final night.", "capacity": 4000, "image": "sports.jpg"},
    {"title": "Sports", "location": "MCA Stadium, Pune", "description": "Corporate golf tournament & gala dinner.", "capacity": 500, "image": "sports.jpg"},
    {"title": "Sports", "location": "Eden Gardens, Kolkata", "description": "T20 charity match & fan zone.", "capacity": 6000, "image": "sports.jpg"},
    {"title": "Sports", "location": "SAI Complex, Chennai", "description": "Marathon after-party with live DJ.", "capacity": 2000, "image": "sports.jpg"},
    {"title": "Sports", "location": "KIIT Stadium, Bhubaneswar", "description": "Hockey World Cup screening event.", "capacity": 1500, "image": "sports.jpg"},
    {"title": "Sports", "location": "Sardar Patel Stadium, Ahmedabad", "description": "IPL viewing party with VIP lounge.", "capacity": 10000, "image": "sports.jpg"},
    {"title": "Sports", "location": "Fatorda Stadium, Goa", "description": "Beach volleyball tournament & afterparty.", "capacity": 800, "image": "sports.jpg"},

    # --- 10 Festival Events ---
    {"title": "Festival", "location": "Vagator Beach, Goa", "description": "EDM Sunburn electronic music festival.", "capacity": 10000, "image": "festival.jpg"},
    {"title": "Festival", "location": "Hauz Khas Village, Delhi", "description": "Cultural night with Diwali light show.", "capacity": 2000, "image": "festival.jpg"},
    {"title": "Festival", "location": "Nandi Hills, Bangalore", "description": "Organic food & wine fiesta under stars.", "capacity": 1500, "image": "festival.jpg"},
    {"title": "Festival", "location": "Marine Drive, Mumbai", "description": "New Year countdown mega celebration.", "capacity": 5000, "image": "festival.jpg"},
    {"title": "Festival", "location": "Hawa Mahal Grounds, Jaipur", "description": "Rajasthani folk & Sufi music festival.", "capacity": 3000, "image": "festival.jpg"},
    {"title": "Festival", "location": "Mahabalipuram Beach, Chennai", "description": "International dance carnival.", "capacity": 2500, "image": "festival.jpg"},
    {"title": "Festival", "location": "Victoria Memorial, Kolkata", "description": "Durga Puja art & music fest.", "capacity": 4000, "image": "festival.jpg"},
    {"title": "Festival", "location": "Lakefront, Bhopal", "description": "Holi color run & pool party.", "capacity": 1800, "image": "festival.jpg"},
    {"title": "Festival", "location": "Jatayu Centre, Kochi", "description": "Onam harvest festival with boat races.", "capacity": 2200, "image": "festival.jpg"},
    {"title": "Festival", "location": "Rock Garden, Chandigarh", "description": "Indie music & street art festival.", "capacity": 3500, "image": "festival.jpg"},

    # --- 10 Charity Events ---
    {"title": "Charity", "location": "Taj Mahal Palace, Mumbai", "description": "Hope Foundation black-tie gala dinner.", "capacity": 300, "image": "charity.jpg"},
    {"title": "Charity", "location": "India Habitat Centre, Delhi", "description": "Green Earth tree-plantation fundraiser.", "capacity": 500, "image": "charity.jpg"},
    {"title": "Charity", "location": "Infosys Campus, Bangalore", "description": "Tech for Good: coding hackathon for charity.", "capacity": 400, "image": "charity.jpg"},
    {"title": "Charity", "location": "HICC, Hyderabad", "description": "Art for Cause: silent auction fundraiser.", "capacity": 250, "image": "charity.jpg"},
    {"title": "Charity", "location": "Lavasa, Pune", "description": "Charity marathon & wellness retreat.", "capacity": 1000, "image": "charity.jpg"},
    {"title": "Charity", "location": "Science City, Kolkata", "description": "Children's education benefit concert.", "capacity": 600, "image": "charity.jpg"},
    {"title": "Charity", "location": "Convention Centre, Chennai", "description": "Cancer awareness walkathon & talk.", "capacity": 800, "image": "charity.jpg"},
    {"title": "Charity", "location": "KIIT, Bhubaneswar", "description": "Rural development donation drive.", "capacity": 350, "image": "charity.jpg"},
    {"title": "Charity", "location": "Sabarmati Ashram, Ahmedabad", "description": "Peace & harmony community gathering.", "capacity": 450, "image": "charity.jpg"},
    {"title": "Charity", "location": "Amber Fort Lawns, Jaipur", "description": "Heritage preservation gala night.", "capacity": 400, "image": "charity.jpg"},
]
